0 CALL2107:REM :MAGIC GOSUB:BY IVAN X::DON'T MODIFY 0-9!.....FOFOFOFOFOFOFOFOFO$O%O8IF*XX*&B*&B*&B*&B*&B*&B*&B*&B%O8IT*XX*&@*&@*&@*&@*&@*&@*&@*&@%O8IB*XX*&;*&;*&;*&;*&;*&;*&;*&;%OE;*&>*&>*&>*&>*&>*&>*&>*&>%OIC*&?*&?*&?*&?*&?*&?*&?*&?%OIDP!
1 REM ##########################*&<*&<*&<*&<*&<*&<*&<*&<%OJI4*XX*&:*&:*&:*&:*&:*&:*&:*&:%OE:*&=*&=*&=*&=*&=*&=*&=*&=%O8IT*XX*&@*&@*&@*&@*&@*&@*&@*&@%OJI0*XX*&E*&E*&E*&E*&E*&E*&E*&E%OI$JJXXH%O8I/*8*H%OH@
2 REM %OJIT*XX*&A*&A*&A*&A*&A*&A*&A*&A%OI(JJXXH%OI0JJXXH%OI)XXXXH%OI4JJXXH%OHI:H%OH@%OJIU*XX*&A*&A*&A*&A*&A*&A*&A*&A%OI(JJXXH%OIZXXXXH%OJI6*XXH%OI0JJXXH%OHI:H%OH@%O8IT*XX*&V*&V*&V*&V*&V*&V*&V*&V%OI4JJXX*&W*&W*&W*&W*&W*&W*&W*&WP2
3 REM %OI<JJXXX%O8ID*XXX%OX%OI<JJXXH%O8IZ*XXH%OH@%O8IN*XX*&A*&A*&A*&A*&A*&A*&A*&A%OI,JJXXH%OI8JXXXH%O8I-*XXH%OI4JJXXH%OHI:H%OH@%OJI:*X**&A*&A*&A*&A*&A*&A*&A*&A%OI,JJXXH%OJI5*XXH%O8I/*XXH%OI4JJXXH%OHI:H%OH@%OI,JJXXH%OJID*XXH%OH@
4 REM %OJI2*X**&A*&A*&A*&A*&A*&A*&A*&A%OI,JJXXH%OJI5*8*H%OIBXXXXH%OI4JJXXH%OHI:H%OH@*&A*&A*&A*&A*&A*&A*&A*&A%OI0JJXXH%OI6JXXXH%OJI/*XXH%OI4JJXXH%OHI:H%OH@%OJIE*XX*&A*&A*&A*&A*&A*&A*&A*&A%OI0JJXXH%O8I4*XXH%OJI.*XXH%OI4JJXXH%OHI:H%OH@%OXP!##
5 REM ########################%OI<JJXX*&A*&A*&A*&A*&A*&A*&A*&A%OI0JJXXH%OJI7*8*H%O8I.*XXH%OI4JJXXH%OHI:H%OH@PG
6 REM %O8IL*XX*&V*&V*&V*&V*&V*&V*&V*&V%OI8JJXX*&W*&W*&W*&W*&W*&W*&W*&W%OX%OQV**0D*0W**&Z*&Z*&Z*&ZX%OQV*****&Z*&Z*&Z*&Z%OEZXXXXX%OI4JJXXH%OI*XXXXH%OH@%OI(JJXXH%OJIR*XXH%OH@%OI0JJXXH%O8I9*8*H%OH@
7 REM JIEHHMFL@LHMBI@MHMDB@MJ@@EIIEJ@MHHM@OJJBHJHFDBLJHFCLJB@OHFDCHFCMJBG@HFCNJBA@HFCODLBLONKJN@OFO@M@HFANKM@F@AHELNKM@G@AHELOJ@@@KALNLID@M@@FHJFI@FJJIJBDCHNFLNM@@BNFLOI@OGJIGCHENNJIA@HENOM@ALAHJ@@AKANNO@FOJJHHKANNI@@KM@@ALJHFKIHEKHLFKHM@P
8 REM HKHFNOHENNJ@@DKANNLIKBM@MLLHKANNLIB@M@@CLHM@OGLIBBO@@MLIECM@@CLHLHLHKANNLIENM@LAIHFENNHENLJENOFI@@HENMJ@@@KALNO@ACLIBBO@@OLIB@O@@KLICJO@@GMANLM@J@LHM@NIKANLO@@LLIBBO@@HLIB@O@@DLICJM@LJCHK@HKJFANKM@D@AHEGEKM@E@AHEGFJIMIDHJIGKDHM@HL@@0
9 REM #########################################################################################################################################################################################################################################

100 REM "INIT"
110 TEXT : HOME
120 LET D$ = CHR$(4)
130 LET X = 11

200 REM "MAIN_LOOP"
210 GOSUB "SHOW_MENU"
220 IF CH$ =  "1" THEN LET G$ = "ROCKET PILOT" : GOSUB "SPAWNER"
230 IF CH$ =  "2" THEN LET G$ = "STAR WARS"    : GOSUB "SPAWNER"
240 IF CH$ =  "3" THEN LET G$ = "LITL RED BUG" : GOSUB "SPAWNER"
250 IF CH$ =  "4" THEN LET G$ = "GALACTI_CUBE" : GOSUB "SPAWNER"
260 IF CH$ =  "5" THEN LET G$ = "SHOW SOURCES" : GOSUB "SHOW_SOURCES"
270 IF CH$ <> "6" THEN GOTO "@MAIN_LOOP"
280 END

300 REM "SHOW_MENU"
310 LET S$ = "BOB BISHOP COLLECTION 1" : GOSUB "TITLE_BAR"
320 HTAB X : PRINT "[1] ROCKET PILOT"
330 HTAB X : PRINT "[2] STAR WARS"
340 HTAB X : PRINT "[3] LIT'L RED BUG"
350 HTAB X : PRINT "[4] GALACTI-CUBE"
360 HTAB X : PRINT "[5] SHOW SOURCES"
370 HTAB X : PRINT "[6] QUIT TO DOS"
380 GOSUB "PRINT_BAR"
390 VTAB 22: LET S$ = "(PRESS CTRL-C FROM WITHIN GAME" : GOSUB "PRINT_CENTERED"
400 VTAB 23: LET S$ = "TO RETURN TO THIS MENU)" : GOSUB "PRINT_CENTERED"
410 VTAB 14 : HTAB X
420 INPUT "ENTER CHOICE:"; CH$
430 RETURN

500 REM "SPAWNER"
510 HOME
520 PRINT "INFO> LOADING "; G$; "..."
530 PRINT D$; "EXEC "; G$
540 END

600 REM "SHOW_SOURCES"
610 LET S$ = "SOURCES" : GOSUB "TITLE_BAR"
620 RESTORE
630 FOR I = 1 TO 4
640     READ S$: LET S$ = " " + S$ + " " : INVERSE : GOSUB "PRINT_CENTERED"
650     READ S$: NORMAL : GOSUB "PRINT_CENTERED"
660     READ S$: GOSUB "PRINT_CENTERED" : PRINT
670 NEXT
680 GOSUB "HIT_ANY_KEY"
690 RETURN

700 REM "SOURCES"
710 DATA ROCKET PILOT,KILOBAUD JANUARY 1978,'THE VERY FIRST APPLE HI-RES GAME!'
720 DATA STAR WARS,KILOBAUD FEBRUARY 1978,'THE SECOND APPLE HI-RES GAME!'
730 DATA LIT'L RED BUG,CREATIVE COMPUTING JANUARY 1981,'AUTHORED AS BISH BOBHOP'
740 DATA GALICTI-CUBE,MICRO NOVEMBER 1981,'3-D MAZE GAME'

800 REM "PRINT_BAR"
810 PRINT "________________________________________"
820 RETURN

900 REM "PRINT_CENTERED"
910 HTAB 20 - LEN(S$) / 2 : PRINT S$
920 RETURN

1000 REM "TITLE_BAR"
1010 HOME
1020 GOSUB "PRINT_BAR"
1030 GOSUB "PRINT_CENTERED"
1040 GOSUB "PRINT_BAR" 
1050 RETURN

1100 REM "HIT_ANY_KEY"
1110 HTAB 13 : VTAB 23 : INVERSE : PRINT " HIT ANY KEY "; : NORMAL : CALL -756
1120 RETURN
