5 REM RUN THIS IN APPLESOFT TO CREATE EXEC FILE
10 LET D$=CHR$(4)
20 PRINT D$;"OPEN LITL RED BUG"
30 PRINT D$;"WRITE LITL RED BUG"
40 PRINT "MON C,I,O"
50 PRINT "BRUN INTBASIC"
60 PRINT "BLOAD LRB_TITLE"
70 PRINT "RUN LRB_MAIN"
80 PRINT "FP"
90 PRINT "TEXT"
100 PRINT "HOME"
110 PRINT "RUN HELLO"
120 PRINT D$;"CLOSE LITL RED BUG"
130 END
