5 REM RUN THIS IN APPLESOFT TO CREATE EXEC FILE
10 LET D$ = CHR$(4)
20 PRINT D$;"OPEN GALACTI_CUBE"
30 PRINT D$;"WRITE GALACTI_CUBE"
40 PRINT "MON C,I,O"
50 PRINT "BRUN INTBASIC"
60 PRINT "RUN GC_MAIN"
70 PRINT "FP"
80 PRINT "HOME"
90 PRINT "RUN HELLO"
100 PRINT D$;"CLOSE GALACTI_CUBE"
110 END
